**Este código importa y estandariza las variables de *unidades.xlsx***

In [1]:
import pandas as pd
import pathlib
import janitor
import unidecode

La siguiente celda de código contiene líneas que separan las rutas relativas de la raíz. Esto es epecialmente útil en casos de trabajo colaborativo, ya que solo es necesario modificar una vez la ruta del objeto llamado *here*. Por ejemplo, si varias personas estuvieran trabajando en un repositorio que contiene este código, modificarían la ruta de here por la ruta en la que tienen clonado el repositorio en su máquina local, y el resto de rutas permanecerían igual.

In [3]:
# Setup

here = pathlib.Path("/Users/macbookair/Documents/prueba-micronegocios/importar").resolve().parent

unidades_path = here/'importar/input/unidades.xlsx'
output = here/'importar/output/unidades.xlsx'

In [7]:
# Leer datos 

unidades = pd.read_excel(unidades_path).clean_names()
unidades.head()

/opt/anaconda3/lib/python3.12/site-packages/openpyxl/packaging/core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/packaging/core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()

,id_micronegocio,sexo,fecha_de_nacimiento,nivel_educativo,grupo_etnico,estado_civil,localidad,lugar_actividades,medio_comercializacion,sector_economico,fecha_inicio_operaciones
0,0,Mujer,1947-08-19,doctorado,Raizal del archipiélago de San Andrés,Casado,RAFAEL URIBE URIBE,Local arrendado,Eventos,Tecnología,2023-10-27
1,1,Hombre,2005-06-16,Ninguno,Raizal del archipiélago de San Andrés,Unión libre,ENGATIVÁ,Kiosko,Vehículo propio,Moda,2023-05-02
2,2,Hombre,1991-03-24,Secundaria,Raizal del archipiélago de San Andrés,Casado,TUNJUELITO,Kiosko,Vehículo propio,Moda,2019-08-17
3,3,Hombre,1945-11-12,Ninguno,otro,Casado,SAN CRISTÓBAL,Local arrendado,Internet,Tecnología,2023-04-26
4,4,Hombre,1997-08-06,doctorado,otro,Unión libre,BOSA,Local arrendado,Eventos,Internet de las cosas,2019-03-09

In [9]:
# Estandarización: mayúsculas y tildes

unidades = unidades.map(lambda x: unidecode.unidecode(x).lower() if isinstance(x, str) else x)

In [13]:
unidades.head()

,id_micronegocio,sexo,fecha_de_nacimiento,nivel_educativo,grupo_etnico,estado_civil,localidad,lugar_actividades,medio_comercializacion,sector_economico,fecha_inicio_operaciones
0,0,mujer,1947-08-19,doctorado,raizal del archipielago de san andres,casado,rafael uribe uribe,local arrendado,eventos,tecnologia,2023-10-27
1,1,hombre,2005-06-16,ninguno,raizal del archipielago de san andres,union libre,engativa,kiosko,vehiculo propio,moda,2023-05-02
2,2,hombre,1991-03-24,secundaria,raizal del archipielago de san andres,casado,tunjuelito,kiosko,vehiculo propio,moda,2019-08-17
3,3,hombre,1945-11-12,ninguno,otro,casado,san cristobal,local arrendado,internet,tecnologia,2023-04-26
4,4,hombre,1997-08-06,doctorado,otro,union libre,bosa,local arrendado,eventos,internet de las cosas,2019-03-09

In [17]:
# Save 

unidades.to_excel(output, index=False)

/opt/anaconda3/lib/python3.12/site-packages/openpyxl/packaging/core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()
/opt/anaconda3/lib/python3.12/site-packages/openpyxl/writer/excel.py:292: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  workbook.properties.modified = datetime.datetime.utcnow()